services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: patrol
      POSTGRES_PASSWORD: password

  validator:
    init: true
    depends_on:
      - db
    image: public.ecr.aws/c9f7n4n0/patrol/validator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      DB_URL: postgresql+asyncpg://patrol:password@db:5432/patrol
      ENABLE_AUTO_UPDATE: 1
      # WALLET_NAME: my_wallet
      # HOTKEY_NAME: my_hotkey
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
