services:
  validator:
    init: true
    image: public.ecr.aws/c9f7n4n0/patrol/validator:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      DB_URL: postgresql+asyncpg://${DB_USERNAME:-patrol}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME:-patrol}
      ENABLE_AUTO_UPDATE: 1
      # WALLET_NAME: my_wallet
      # HOTKEY_NAME: my_hotkey
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /var/run/docker.sock:/var/run/docker.sock
